### PR TITLE
Updated FacetsForm.tsx and tsconfig

### LINKED ISSUE #280: Fix wording of search fields for better clarity
### Describe the fix

Rename “Filename Variable” to “Filename Search” –> non-CMIP6 datasets don’t have variable name in the filename

### PR DESCRIPTION
**Pull request by downiec**
## Description

Changes 'filename variables' to 'filename search'. Includes minor fix to tsconfig so yarn start:local runs correctly.

Fixes #280 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

- [ ] Local Pre-commit Checks
- [ ] CI/CD Build

## Checklist

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by tomvothecoder — APPROVED** [review]
Looks good to squash and merge

**Comment by tomvothecoder** [comment]
Hey @downiec, I noticed you forgot to squash before merging. You can create a branch off of `master` to squash those commits and open a new PR to merge. 

It slows down dev a little bit but it ensures each commit passes the CI build and keeps the git history clean.

**Comment by downiec** [comment]
Yeah I accidentally clicked merge and rebase (it was the default). I'll try that now

**Comment by tomvothecoder** [comment]
@downiec Cool thanks!

**Comment by downiec** [comment]
@tomvothecoder https://github.com/aims-group/metagrid/pull/293

**Pull request merged**
