### PR TITLE
Feature/138 subscription service

### PR DESCRIPTION
**Pull request by downiec**
## Description

This PR  integrates the subscription service in MetaGrid using the `esgf-subscriptions` package from npm. This also involves integrating new MetaGrid APIs and Celery tasks for retrieving CVs and sending notifications.

- Closes #183 

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

### Back-end
Subscriptions App
  - [x] Add Subscriptions app and update Django config
  - [x] Add models, viewsets, routes for `SavedSubscriptions` model
  - [x] Add model migration files and data migration to link subscription objects to existing users 
  - [x] Update `urls.py` to connect Subscriptions viewsets to router 
  - [x] Add tests for 100% coverage

CVs API
- [ ] Scope out solutions on how to pull in CVs -- pulls from the GitHub CVs repo: [Link](https://github.com/WCRP-CMIP/CMIP6_CVs)
- [ ] Add and configure Celery in the background 
- [ ] Add REST API endpoints for CVs

Notifications (Celery Task)
- TBD

### Front-end
Subscriptions Components Integration
- [x] Add `esgf-subscriptions` package to `package.json` dependencies
- [x] Integrate `Subscriptions` components
- [x] Add method to handle creating subscriptions
- [x] Add method to handle deleting subscriptions
- [x] Add API based functions for performing requests
- [x] Add/update tests for 100% coverage

CVs API
- [ ] Add HTTP request function to CVs API
- [ ] Update `Subscriptions` components to call CVs API

## How Has This Been Tested?

- [x] Pre-commit (ESLint, Prettier, Flake8, Black, Mypy)
- [ ] CI/CD Build

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tomvothecoder** [comment]
@downiec sorry for the delay, I will be able to go through your changes next week.

It looks like you performed some merge commits which caused the branch to show changes from master as being new when they aren't (reference 'Files Changed' tab).

To get rid of those merge commits and rebase onto master for a cleaner branch using the squash and rebase workflow:
1. Pull latest master: `git pull origin master`
2. Checkout your branch
3. Figure out the SHA of the commit to rebase to (usually the commit before your first commit), use `git log --oneline --graph` 
4. Drop the commits related to merging master using `git rebase -i [SHA]`
5. Update commit messages as needed
6. Force push to remote `git push origin feature/138-subscription-service`
7. Rebase with master: `git rebase master` (fix merge conflicts as needed)
8. Force push to remote `git push origin feature/138-subscription-service`

More info here: https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/

**Comment by tomvothecoder** [comment]
> @downiec sorry for the delay, I will be able to go through your changes next week.
> 
> It looks like you performed some merge commits which caused the branch to show changes from master as being new when they aren't (reference 'Files Changed' tab).
> 
> To get rid of those merge commits and rebase onto master for a cleaner branch using the squash and rebase workflow:
> 
> 1. Pull latest master: `git pull origin master`
> 2. Checkout your branch
> 3. Figure out the SHA of the commit to rebase to (usually the commit before your first commit), use `git log --oneline --graph`
> 4. Drop the commits related to merging master using `git rebase -i [SHA]`
> 5. Update commit messages as needed
> 6. Force push to remote `git push origin feature/138-subscription-service --force`
> 7. Rebase with master: `git rebase master` (fix merge conflicts as needed)
> 8. Force push to remote `git push origin feature/138-subscription-service --force`
> 
> More info here: https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/

It looks like you might have coupled changes with the merge commits, so you can probably just do steps 1, 7, and 8 instead. Then we can squash the branch at the end before we merge the PR.

**Comment by downiec** [comment]
@tomvothecoder, I'll go ahead and try what your saying. I'm still actively developing this branch and have been trying to get the API going and maybe we can go over this sometime this or next week to make sure it's matching the structure.

**Comment by tomvothecoder** [comment]
https://stackoverflow.com/questions/10598431/how-to-rebase-after-a-merge

We followed this guide to rebase on top of master

**Comment by tomvothecoder** [comment]
@downiec I've updated the issue description with a checklist for the PR.

**Pull request closed without merging**
